version: '3.8'

services:
  portfolio:
    image: melihemreguler/portfolio:latest
    container_name: portfolio-app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=melihemre.dev,www.melihemre.dev
      - LETSENCRYPT_HOST=melihemre.dev,www.melihemre.dev
      - LETSENCRYPT_EMAIL=guler@melihemre.dev
    networks:
      - web

  # test service for IP access without nginx-proxy
  portfolio-test:
    image: melihemreguler/portfolio:latest
    container_name: portfolio-test
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    profiles:
      - test

networks:
  web:
    external: true
